language: haskell

ghc:
    - 7.10.1


before_install:
    - |
      bash <(curl -sS https://nixos.org/nix/install)
      source $HOME/.nix-profile/etc/profile.d/nix.sh
      nix-channel --update

install:
    - nix-shell -p '(haskellngPackages.callPackage ./default.nix { })' --command 'exit 0'

script: true
