# This file was auto-generated by cabal2nix. Please do NOT edit manually!
{ cabal, process, dataDefault, filepath, cereal, lens, random }:  

cabal.mkDerivation (self: {
  pname = "gShell";
  version = "0.0.0.0.0.0.1";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ cereal dataDefault filepath lens random process ];
  meta = {
    homepage = "https://github.com/ctlab/gShell";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
